const mealsMock = [
  {
    idMeal: '53060',
    strMeal: 'Burek',
    strDrinkAlternate: null,
    strCategory: 'Side',
    strArea: 'Croatian',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
    strTags: 'Streetfood, Onthego',
    strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
    strIngredient1: 'Filo Pastry',
    strIngredient2: 'Minced Beef',
    strIngredient3: 'Onion',
    strIngredient4: 'Oil',
    strIngredient5: 'Salt',
    strIngredient6: 'Pepper',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 Packet',
    strMeasure2: '150g',
    strMeasure3: '150g',
    strMeasure4: '40g',
    strMeasure5: 'Dash',
    strMeasure6: 'Dash',
    strMeasure7: ' ',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53026',
    strMeal: 'Tamiya',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Egyptian',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
    strIngredient1: 'Broad Beans',
    strIngredient2: 'Spring Onions',
    strIngredient3: 'Garlic Clove',
    strIngredient4: 'Parsley',
    strIngredient5: 'Cumin',
    strIngredient6: 'Baking Powder',
    strIngredient7: 'Cayenne Pepper',
    strIngredient8: 'Flour',
    strIngredient9: 'Vegetable Oil',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '3 cups ',
    strMeasure2: '6',
    strMeasure3: '4',
    strMeasure4: '1/4 cup',
    strMeasure5: '2 tsp',
    strMeasure6: '1 tsp ',
    strMeasure7: '1/2 tsp',
    strMeasure8: 'Spinkling',
    strMeasure9: 'As required',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53027',
    strMeal: 'Koshari',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Egyptian',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/4er7mj1598733193.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=y0d2ZMZBW4Y',
    strIngredient1: 'Brown Lentils',
    strIngredient2: 'Rice',
    strIngredient3: 'Coriander',
    strIngredient4: 'Macaroni',
    strIngredient5: 'Chickpeas',
    strIngredient6: 'Onion',
    strIngredient7: 'Salt',
    strIngredient8: 'Vegetable Oil',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 1/2 cups ',
    strMeasure2: '1 1/2 cups ',
    strMeasure3: '1/2 tsp',
    strMeasure4: '2 cups ',
    strMeasure5: 'Can',
    strMeasure6: '1 large',
    strMeasure7: 'Sprinking',
    strMeasure8: '1/2 cup ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.themediterraneandish.com/egyptian-koshari-recipe/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

export default mealsMock;
